- name: Run Scan Script
      env:
        # ชื่อนี้ต้องตรงกับที่เขียนใน if 'GOOGLE_APPLICATION_CREDENTIALS' in os.environ:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: python "App 15.py"
